### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by quadrupleslap** [dylanede/cef-rs#11]
Is this project abandoned?

**Comment by dOrgJelli** [comment]
Wondering this as well, any suggestions? Was looking at Servo too...

**Comment by hamaluik** [comment]
Certainly seems so :disappointed: 

I'm poking around with CEF now and if I can get anything working (the docs for the `c` API are _terrible_), I'll make sure to post it here.

**Comment by hamaluik** [comment]
I have a basic version of `cefsimple` working in Rust here if you need: https://github.com/hamaluik/cefsimple-rs

**Comment by dylanede** [comment]
Yes, this project is not active any more. For rationale on why, see the last time this question was asked, in issue #8.
