### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by dylanede** [dylanede/cef-rs#3]
I have tested cef-sys bindings on Mac and Windows, but I need to run rust-bindgen on Linux before it will work on that platform.

**Comment by palodequeso** [comment]
Can you send me the ffi.h file again, along with the bindgen command to get this going? I think it was my clang version but have since formatted and re-installed linux and forgot to back this information up.

**Comment by dylanede** [comment]
OK. The ffi.h is [here](https://gist.github.com/dylanede/15a9e7da6a3ace9f9fd2). The command to run is
```
bindgen ffi.h -I include -I include/capi -o ffi.rs -match cef_
```

And, most importantly, the version of CEF required is **3.2271.1981**, downloadable from [here](http://www.cefbuilds.com). Click on *More revisions* to get the list of older versions.

Thanks!

**Comment by palodequeso** [comment]
Crap, same exact issue.
```
douglas@douglas-lappy:~/Downloads/cef_binary_3.2271.1981_linux64$ LD_PRELOAD=/usr/lib/libclang.so bindgen ffi.h -I include -I include/capi -o ffi.rs -match cef_
include/capi/cef_app_capi.h:41:10: fatal error: 'include/capi/cef_base_capi.h' file not found
ERROR:bindgen: include/capi/cef_app_capi.h:41:10: fatal error: 'include/capi/cef_base_capi.h' file not found
```

**Comment by dylanede** [comment]
Hmm. Maybe try using `./include` instead of `include` for local paths?

**Comment by palodequeso** [comment]
No dice.

**Comment by dylanede** [comment]
See my edit to my comment.

**Comment by palodequeso** [comment]
This is what I tried:
```
LD_PRELOAD=/usr/lib/libclang.so bindgen ffi.h -I /home/douglas/Downloads/cef_binary_3.2271.1981_linux64/include -I /home/douglas/Downloads/cef_binary_3.2271.1981_linux64/include/capi -o ffi.rs -match cef_
```

I still get the same error.

**Comment by dylanede** [comment]
Ah, maybe you should add `-I .`.

**Comment by dylanede** [comment]
So the command should be
bindgen ffi.h -I . -I include -I include/capi -o ffi.rs -match cef_

**Comment by palodequeso** [comment]
That makes a lot of sense, now it's complaining about some other missing header:
```
douglas@douglas-lappy:~/Downloads/cef_binary_3.2271.1981_linux64$ LD_PRELOAD=/usr/lib/libclang.so bindgen ffi.h -I . -I include -I include/capi -o ffi.rs -match cef_
/usr/include/limits.h:123:16: fatal error: 'limits.h' file not found
ERROR:bindgen: /usr/include/limits.h:123:16: fatal error: 'limits.h' file not found
```

What's interesting is limits.h is definitely in `/usr/include`. I'm wondering if clang needs some other ordering for it to use the right one first.

**Comment by dylanede** [comment]
Try adding `-I /usr/include`.

**Comment by jdm** [comment]
My experience with rust-bindgen is that I occasionally need to include arguments like `-isystem /usr/lib/gcc/x86_64-redhat-linux/4.7.0/include/` to get it to find the right system headers. See https://github.com/servo/rust-mozjs/blob/master/gen.py for an example.

**Comment by palodequeso** [comment]
> Try adding -I /usr/include.

Unfortunately, that didn't work either.

> My experience with rust-bindgen is that I occasionally need to include arguments like -isystem /usr/lib/gcc/x86_64-redhat-linux/4.7.0/include/ to get it to find the right system headers. See https://github.com/servo/rust-mozjs/blob/master/gen.py for an example.

I'll give that a go.

**Comment by dylanede** [comment]
Then maybe it should be `-isystem /usr/include`

**Comment by jdm** [comment]
@dylanede It seems to be finding /usr/include/limits.h already, since that's where the error is. I'm presuming the line in question is an `#include_next` or whatever gcc uses to forward to a special system header.

**Comment by palodequeso** [comment]
nah, it has to point to the actual include files, not anything wrapping those files:
Check out https://github.com/servo/rust-mozjs/blob/master/gen.py

I'm going to try to make it mimic that.

**Comment by palodequeso** [comment]
This worked:
```
LD_PRELOAD=/usr/lib/libclang.so bindgen ffi.h -I . -I include -I include/capi -o ffi.rs -match cef_ -isyem /usr/lib/llvm-3.5/lib/clang/3.5.0/include/
```

https://gist.github.com/palodequeso/c13b08b8e95a968fc7dd

**Comment by palodequeso** [comment]
@dylanede is that what you needed?

**Comment by dylanede** [comment]
That should do the trick, thanks! I don't have the time immediately to check the validity of the result but I should be able to within the next hour. Thanks again!

**Comment by dylanede** [comment]
@palodequeso Could you try the linux_support branch to see if this works? Be warned that this is probably a few nightlies behind. I haven't tested with the latest one to see if anything is broken.

**Comment by palodequeso** [comment]
I made a comment on the branch. :)
